### ISSUE TITLE
The RecyclerViews desynchronize after a simple tap

### ISSUE THREAD

**Issue by sea-cat** [stoyicker/RecyclerViewSyncDemo#1]
The behaviour I noticed is that on tap on the view on the right, the left one moves a little faster. The more you single tap, the faster the left one scrolls compared to the other one. This difference is reseted after reaching the end of the lists.

I've been looking for a solution. I guess the problem is because on simple tap, the onInterceptTouchEvent method is called, and because the recycler is idle (both not scrolling at the moment),  onTouchEvent is called and it adds another scroll listener. I tried adding a clear to both recyclers before adding the listener and it worked better, but still not perfect( but i also had different length recyclers so maybe that was an issue too). You should probably clear before adding listeners.

It also happens in the demo app that you have on the store. I used a 4.4 and a 5.0 to test and both have the same behaviour.

**Comment by stoyicker** [comment]
On it.
