### ISSUE TITLE
desynk on short scroll

### ISSUE THREAD

**Issue by sea-cat** [stoyicker/RecyclerViewSyncDemo#3]
Now I've noticed that if you scroll only a little, they desynchronize with the amount you scrolled. I managed this while trying to simple tap, but dragged the finger a little, about 5-15dp. Android 4.4
Also it crashes but I haven't found a pattern yet. Something to do with adding and removing elements. I'll open another issue if I see the pattern.
Best of luck!

**Comment by stoyicker** [comment]
Have you reproduced that desync you talk about in the sample app? I can't get to do so.

**Comment by sea-cat** [comment]
yes, on the updated sample app. try tapping rapidly with minimal dragging. if you want i can make a video

**Comment by stoyicker** [comment]
Alright, I got to reproduce it once now. Not like it's any easy to pop it up, but it's definitely there. It doesn't come straight to mind why it happens, but I might be able to put up a bit of time together to research on it in a few days. Please keep me posted if you gather any further information.

**Comment by sea-cat** [comment]
I haven't connected it to the debugger, but if i do and notice something,
i'll let you know. I manage to reproduce this quite easily though :)
