### ISSUE TITLE
is there a way to make this dynamic?

### ISSUE THREAD

**Issue by adfleshner** [stoyicker/RecyclerViewSyncDemo#4]
Currently this is two statically typed RecyclerViews is there any chance that you looking into a dynamic version of this so that RecyclerViews can be added and removed programmatically?

**Comment by stoyicker** [comment]
You should be able to extend the pattern pretty easily with very little effort. If still you don't want to work on it, stay tuned on https://github.com/stoyicker/AligningRecyclerView (not available yet).
