### ISSUE TITLE
Problemas para ejecutar el proyecto

### ISSUE THREAD

**Issue by oreyne** [stoyicker/RecyclerViewSyncDemo#5]
Este proyecto me es útil para algo que necesito hacer, pero cuando descargo el proyecto, y lo abro con el Android Studio 2.2, sucede el siguiente problema sincronizando el Gradle:

Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

lo único que he cambiado en el build.gradle es la linea 8 que puse esto:

classpath 'com.android.tools.build:gradle:2.2.2'

pero en su estado original, me sigue dando el mismo error.

**Comment by stoyicker** [comment]
Please write in english as this may be helpful for others in the future.

Make sure you have a perfectly working internet connection.
First off, make sure all files are on its original state (like the `build.gradle` that you state you have modified).
Close Android Studio.
If you're using Linux or Mac OS, open your terminal and type `rm -rf ~/.gradle`. If you're using Windows I don't think I can help you in this step.
Open the project in Android Studio, and in the top menu press `File` > `Invalidate Caches / Restart` and choose `Invalidate and Restart` in the dialog that comes up. This will take a few minutes, **be patient and wait until Android Studio restarts and there are no loading bars in progress**.

**Comment by oreyne** [comment]
I'm sorry, I'm using Windows and I have a good internet connection. I did what you told me but the problem persists. I do not know what the problem might be.
